# Generated by Django 5.0.7 on 2024-07-28 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('type', models.CharField(choices=[('legal', 'Legal'), ('individual', 'Individual')], default='legal', max_length=200, verbose_name='Type')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_moderation', 'In Moderation'), ('declined', 'Declined'), ('accepted', 'Accepted')], default='new', max_length=200, verbose_name='Status')),
                ('amount', models.PositiveBigIntegerField(default=5000, verbose_name='Amount')),
                ('company', models.CharField(blank=True, max_length=200, null=True, verbose_name='Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
            },
        ),
    ]
