# Generated by Django 5.0.7 on 2024-07-28 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='amount',
            field=models.PositiveIntegerField(default=5000, verbose_name='Amount'),
        ),
        migrations.CreateModel(
            name='SponsorShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('amount', models.PositiveIntegerField(default=5000, verbose_name='Amount')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship', to='sponsor.sponsor', verbose_name='Sponsor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to='student.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'SponsorShip',
                'verbose_name_plural': 'SponsorShips',
            },
        ),
    ]
